name: my first workflow

on: push

jobs:
    first-jobs:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repository
          uses: actions/checkout@v5
          
        - name: welcome message
          run: |
            echo "my first workflow"
            ls -ltra
            cat README.md

        # - name: list files
        #   run: ls

        # - name: Read files
        #   run: cat README.md